
  [en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

  [zh]
    contentDir = "content/zh"
    languageName = "中文"
    weight = 2

  [ja]
    contentDir = "content/ja"
    languageName = "日本語"
    weight = 2
