ports:
    - port: 1313
      onOpen: open-preview
tasks:
  - init: >
      mkdir -p /workspace/go/bin &&
      wget -qO- https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz | tar xvz -C /workspace/go/bin
    command: hugo server --bind 0.0.0.0 --liveReloadPort 443
