[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.36"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --enableGitInfo"

[context.deploy-preview.environment]
HUGO_VERSION = "0.36"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.36"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
