[[docs]]
identifier = 'about'
name = 'About'
pageRef = '/about/'
weight = 10

[[docs]]
name = 'Installation'
weight = 20
identifier = 'installation'
pageRef = '/installation/'

[[docs]]
name = 'Getting started'
weight = 30
identifier = 'getting-started'
pageRef = '/getting-started/'

[[docs]]
name = 'Quick reference'
weight = 40
identifier = 'quick-reference'
pageRef = '/quick-reference/'
post = 'break'

[[docs]]
name = 'Content management'
weight = 50
identifier = 'content-management'
post = 'expanded'
pageRef = '/content-management/'

[[docs]]
name = 'Templates'
weight = 60
identifier = 'templates'
pageRef = '/templates/'

[[docs]]
name = 'Functions'
weight = 70
identifier = 'functions'
pageRef = '/functions/'

[[docs]]
name = 'Methods'
weight = 80
identifier = 'methods'
pageRef = '/methods/'

[[docs]]
name = 'Render hooks'
weight = 90
identifier = 'render-hooks'
pageRef = '/render-hooks/'

[[docs]]
name = 'Hugo Modules'
weight = 100
identifier = 'modules'
pageRef = '/hugo-modules/'

[[docs]]
name = 'Hugo Pipes'
weight = 110
identifier = 'hugo-pipes'
pageRef = '/hugo-pipes/'

[[docs]]
name = 'CLI'
weight = 120
post = 'break'
identifier = 'commands'
pageRef = '/commands/'

# Low level items

[[docs]]
name = 'Troubleshooting'
weight = 130
identifier = 'troubleshooting'
pageRef = '/troubleshooting/'

[[docs]]
name = 'Developer tools'
weight = 140
identifier = 'developer-tools'
pageRef = '/tools/'

[[docs]]
name = 'Hosting and deployment'
weight = 150
identifier = 'hosting-and-deployment'
pageRef = '/hosting-and-deployment/'

[[docs]]
name = 'Contribute'
weight = 160
post = 'break'
identifier = 'contribute'
pageRef = '/contribute/'

######## QUICKLINKS

[[quicklinks]]
identifier = 'fundamentals'
name = 'Fundamentals'
pageRef = '/tags/fundamentals/'
weight = 1

######## GLOBAL ITEMS TO BE SHARED WITH THE HUGO SITES

[[global]]
name = 'News'
weight = 1
identifier = 'news'
pageRef = '/news/'

[[global]]
name = 'Docs'
weight = 5
identifier = 'docs'
url = '/documentation/'

[[global]]
name = 'Themes'
weight = 10
identifier = 'themes'
url = 'https://themes.gohugo.io/'

# [[global]]
# name = 'Showcase'
# weight = 20
# identifier = 'showcase'
# pageRef = '/showcase/'

# Anything with a weight > 100 gets an external icon

[[global]]
name = 'Community'
weight = 150
icon = true
identifier = 'community'
post = 'external'
url = 'https://discourse.gohugo.io/'

[[global]]
name = 'GitHub'
weight = 200
identifier = 'github'
post = 'external'
url = 'https://github.com/gohugoio/hugo'
