name: Lint markdown
on:
  workflow_dispatch:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Run Markdown linter
      uses: DavidAnson/markdownlint-cli2-action@v20
      continue-on-error: false
