name: "Check spelling"
on: # rebuild any PRs and main branch changes
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
        with:
          check_dot_files: false
          incremental_files_only: true
          inline: warning
          strict: false
