name: 'Check spelling'
on: # rebuild any PRs and main branch changes
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: streetsidesoftware/cspell-action@3bc52c39528d0214a947ff7f8b5c23ad3273435b
        with:
          inline: warning
          strict: false
          incremental_files_only: true
