name: Super Linter

on:
  workflow_dispatch:

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  build:
    permissions:
      contents: read #  to fetch code (actions/checkout)
      statuses: write #  to mark status of each linter run (github/super-linter/slim)

    name: Lint Code Base
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          LINTER_RULES_PATH: /
          LOG_LEVEL: NOTICE
          MARKDOWN_CONFIG_FILE: .markdownlint.yaml
          SUPPRESS_POSSUM: true
          VALIDATE_CSS: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_GITLEAKS: false
          VALIDATE_HTML: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_XML: false
